-- Estoque minimo manual por insumo (confirmado pelo Alvaro em 05/10/2026):
-- consumo medio diario das 4 semanas de 07/09 a 04/10, arredondado pra cima, com piso de
-- 7 dias de consumo limitado a 1 embalagem. Itens do ciclo de troca (hortifruti) ficam de fora.
INSERT INTO insumo_minimo (insumo, minimo) VALUES
('Bacon', 468),
('Batata Chips', 4),
('Batata Frita', 3995),
('Carne Angus', 60),
('Carne Costela', 1),
('Coca Normal', 4),
('Coca Zero', 8),
('Fanta Laranja', 1),
('Guaraná Normal', 15),
('Guaraná Zero', 12),
('Guardanapo', 52),
('Hambúrguer de Frango', 1),
('Heineken', 1),
('Ketchup', 143),
('Maionese Grill', 1949),
('Maionese de Bacon', 313),
('Molho Barbecue', 31),
('Molho Ervas Finas', 31),
('Molho Parmesão', 8),
('Molho Ranch', 250),
('Mostarda', 143),
('Nuggets', 4),
('Papel Acoplado', 52),
('Papel Kraft', 40),
('Papel de Batata', 27),
('Picles', 14),
('Pudim', 1),
('Pão Australiano', 1),
('Pão Brioche', 49),
('Pão Brioche com Gergelim', 3),
('Queijo Cheddar', 184),
('Queijo Mussarela', 13),
('Sachê de Ketchup', 52),
('Sachê de Mostarda', 52),
('Sachê de Sal', 1),
('Sprite', 3),
('Suco Del Valle Maracujá', 1),
('Suco Del Valle Uva', 1),
('Água Normal', 1),
('Água com Gás', 1)
ON CONFLICT (insumo) DO UPDATE SET minimo = EXCLUDED.minimo;
